services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"       # MinIO Console
      - "9001:9001"       # MinIO Admin Console
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY?Variable not set}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY?Variable not set}
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
  minio-setup:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set myminio http://minio:9000 ${S3_ACCESS_KEY} ${S3_SECRET_KEY}) do sleep 3; done;
      /usr/bin/mc mb myminio/${S3_BUCKET} --ignore-existing;
      "
volumes:
  minio-data:
