@startuml
left to right direction

actor "Student" as Student
actor "Admin" as Admin
actor "Driver" as Driver

rectangle "Client" {
  component "Student App" as MobileStudent
  component "Driver App" as MobileDriver
  component "Admin Dashboard" as WebAdmin
}

component "API Gateway" as APIGW

package "Microservices" {
  component "Auth Service" as Auth
  component "User & Enrollment\nService" as UserSvc
  component "Trip & Route\nService" as TripSvc
  component "Notification Service" as NotifSvc
  component "GPS Ingestion\n& Realtime Service" as GPSSvc
  component "Analytics & Reporting\nService" as AnalyticsSvc
}

component "Spark / Batch\nOptimization Jobs" as Spark

package "Data" {
  component "PostgreSQL\n(Main DB)" as DB
  component "Kafka\n(Message Broker)" as Kafka
  component "Object Storage\n(MinIO)" as S3
}

package "3rd-parties" {
  component "Map/Traffic API" as MapAPI
  component "IdP (Google/Azure)" as IdP
  component "APNS/FCM" as Push
}

Student --> MobileStudent
Driver --> MobileDriver
Admin --> WebAdmin

MobileStudent --> APIGW
MobileDriver --> APIGW
WebAdmin --> APIGW

APIGW --> Microservices

Spark --> Data
Microservices --> Data
Microservices --> "3rd-parties"


@enduml